vich_uploader:
    db_driver: orm
    metadata:
        type: attribute # or annotation
        
    mappings:
        rooms_images:
            uri_prefix: '%rooms_images%'
            upload_destination: '%kernel.project_dir%/public%rooms_images%'
