vich_uploader:
    db_driver: orm
    metadata:
        type: attribute # or annotation
        
    mappings:
        rooms_images:
            uri_prefix: '%rooms_images%'
            upload_destination: '%kernel.project_dir%/public%rooms_images%'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }
        hotels_images:
            uri_prefix: '%hotels_images%'
            upload_destination: '%kernel.project_dir%/public%hotels_images%'
            namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }
