#index:
#    path: /
#    controller: App\Controller\DefaultController::index




#uniq_hotel:
#    pattern:  /hotel/{slug}
#    controller: App\Controller\HotelController::index
#    requirements:
#        _format: html
#        slug: '[a-zA-Z0-9-_/.]+'
